public enum ThingPartAttribute
{
    offersScreen = 1,
    scalesUniformly = 3,
    videoScreenHasSurroundSound = 4,
    isLiquid = 5,
    offersSlideshowScreen = 6,
    isCamera = 8,
    isFishEyeCamera = 10,
    useUnsoftenedAnimations = 11,
    invisible = 12,
    isUnremovableCenter = 13,
    omitAutoSounds = 14,
    doSnapTextureAngles = 15,
    textureScalesUniformly = 16,
    avoidCastShadow = 17,
    looselyCoupledParticles = 18,
    textAlignCenter = 19,
    textAlignRight = 20,
    isAngleLocker = 21,
    isPositionLocker = 22,
    isLocked = 23,
    avoidReceiveShadow = 24,
    isImagePasteScreen = 25,
    allowBlackImageBackgrounds = 26,
    videoScreenLoops = 27,
    videoScreenIsDirectlyOnMesh = 28,
    useTextureAsSky = 29,
    stretchSkydomeSeam = 30,
    subThingsFollowDelayed = 31,
    hasReflectionPartSideways = 32,
    hasReflectionPartVertical = 33,
    hasReflectionPartDepth = 34,
    videoScreenFlipsX = 35,
    persistStates = 36,
    uncollidable = 37,
    isDedicatedCollider = 38,
    personalExperience = 39,
    invisibleToUsWhenAttached = 40,
    lightOmitsShadow = 41,
    showDirectionArrowsWhenEditing = 42,

    // Deprecated as now possible via scripting,
    // will load but not save after clone-editing:
    isVideoButton = 2,
    isSlideshowButton = 7,
    isCameraButton = 9
}
